openapi: 3.0.3
info:
  title: Demo openApi
  description: Demo use open APi for generate REST API endpoints
  version: 0.0.1
servers:
  - url: 'https'
  - url: 'http'
paths:
  /demo:
    get:
      tags:
        - Demo
      summary: Demo Summary
      description: Demo Description
      operationId: fetchAllDemo
      security:
        - oAuth:
            - demo:read:all
      parameters:
        - name: fieldsToExtractCode
          in: query
          required: true
          schema:
            type: string
          description: specify the fields that will be present on the response
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DemoDTO'
  /user:
    post:
      tags:
        - User
      summary: create user
      description: create user
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/UserDTO'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: string
                format: uuid
components:
  schemas:
    DemoDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    UserDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userName:
          type: string
        firstName:
          type: string
        lastName:
          type: string

