openapi: 3.0.3
info:
  title: Demo openApi
  description: Demo use open APi for generate REST API endpoints
  version: 0.0.1
servers:
  - url: 'https'
  - url: 'http'
paths:
  /demo:
    get:
      tags:
        - Demo
      summary: Demo Summary
      description: Demo Description
      operationId: fetchAllDemo
      security:
        - oAuth:
            - demo:read:all
      parameters:
        - name: fieldsToExtractCode
          in: query
          required: true
          schema:
            type: string
          description: specify the fields that will be present on the response
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DemoDTO'

components:
  securitySchemes:
    oAuth:
      type: oauth2
      description: This API uses OAuth 2 with the Authorization Code grant flow.
      flows:
        authorizationCode:
          authorizationUrl: https://auth.oauth.lao-sarl.cm
          tokenUrl: https://token.oauth.lao-sarl.cm
          scopes:
            demo:read:all: Read all Demo
            user:create: Create user
            business:read:all: Read all business
            user:read:all: Read all user
            user:read: Read user
            subscription:create: subscription to a package plan
            edit-business-request:reject: reject edit business request
            category:create: create category and sub category
  schemas:
    DemoDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string

